# Generated by Django 4.2.30 on 2026-09-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Jeseena J', max_length=100)),
                ('professional_title', models.CharField(default='FULL STACK DEVELOPER', max_length=150)),
                ('short_introduction', models.TextField(default='I am a Full Stack Developer with a background in Functional English and hands-on experience building web applications using Python, Django, MySQL, HTML, CSS and JavaScript. I enjoy creating practical, responsive and user-friendly web applications while continuously learning modern web technologies.', help_text='Introduction summary shown in the Hero section')),
                ('about_text', models.TextField(default='I started my journey with a background in Functional English and later moved into full-stack web development. I enjoy turning ideas into functional web applications and continuously improving my development skills.', help_text='Detailed story shown in the About section')),
                ('quote', models.TextField(default='Good code is not just how it looks, but how it works, scales, and delivers real-world utility.', help_text='Editorial quote shown in the About side card')),
                ('location', models.CharField(default='Kerala, India', max_length=100)),
                ('email', models.EmailField(default='jeseena.dev@gmail.com', max_length=254)),
                ('github_url', models.URLField(blank=True, default='https://github.com', max_length=500)),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com', max_length=500)),
                ('profile_photo', models.ImageField(blank=True, help_text='Upload your personal portrait', null=True, upload_to='profile/')),
                ('years_old', models.CharField(blank=True, default='21+', max_length=20)),
                ('featured_projects_count', models.CharField(blank=True, default='2+', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Me Profile',
                'verbose_name_plural': 'About Me Profile',
            },
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='e.g. 2022, 2025, 2025 – 2026, 2026', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Journey Milestone',
                'verbose_name_plural': 'Journey Milestones',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.CharField(default='01', help_text='e.g. 01, 02', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Work Process Step',
                'verbose_name_plural': 'Work Process Steps',
                'ordering': ['order', 'id'],
            },
        ),
    ]
