# Generated by Django 4.2.30 on 2026-09-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_about_journey_workprocess'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_number', models.CharField(default='01', help_text='e.g. 01, 02', max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('skills_list', models.CharField(blank=True, help_text='Technologies e.g. HTML, CSS, JavaScript, React', max_length=300)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'What I Do (Capability)',
                'verbose_name_plural': 'What I Do (Capabilities)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', 'category', 'name'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AddField(
            model_name='skill',
            name='proficiency',
            field=models.PositiveIntegerField(default=75, help_text='Proficiency percentage (e.g. 80 for 80%)'),
        ),
    ]
