# Generated by Django 4.2.30 on 2026-09-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_service_alter_skill_options_skill_proficiency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Jeseena - Full Stack Developer CV', max_length=150)),
                ('file', models.FileField(help_text='Upload or replace your CV PDF here', upload_to='resumes/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='If checked, this CV will be provided to all Download CV buttons')),
            ],
            options={
                'verbose_name': 'Resume / CV',
                'verbose_name_plural': 'Resume / CV',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='is_learning',
            field=models.BooleanField(default=False, help_text='Check if currently learning this technology'),
        ),
        migrations.AddField(
            model_name='skill',
            name='learning_note',
            field=models.CharField(blank=True, help_text='e.g. Currently learning React or Currently learning Node.js', max_length=255),
        ),
        migrations.AddField(
            model_name='skill',
            name='learning_progress',
            field=models.PositiveIntegerField(default=0, help_text='Learning progress percentage (e.g. 35 for React)'),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_text',
            field=models.TextField(default='I completed intensive Python Full Stack Development training with an internship at Safe Technologies. I have practical experience building dynamic web applications using Python, Django, and MySQL. I enjoy creating practical, responsive, and user-friendly web applications, and I am currently expanding my skills into React, Node.js, and modern APIs to continuously grow as a Full Stack Developer.', help_text='Detailed story shown in the About section'),
        ),
        migrations.AlterField(
            model_name='about',
            name='email',
            field=models.EmailField(default='jeseena2005@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='about',
            name='featured_projects_count',
            field=models.CharField(blank=True, default='3', max_length=20),
        ),
        migrations.AlterField(
            model_name='about',
            name='github_url',
            field=models.URLField(blank=True, default='https://github.com/Jeseena-codes', max_length=500),
        ),
        migrations.AlterField(
            model_name='about',
            name='linkedin_url',
            field=models.URLField(blank=True, default='https://linkedin.com/in/jeseena-j-48a126336', max_length=500),
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(default='Jeseena', max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='professional_title',
            field=models.CharField(default='Full Stack Developer', max_length=150),
        ),
        migrations.AlterField(
            model_name='about',
            name='quote',
            field=models.TextField(default='Build. Learn. Improve. Repeat.', help_text='Quote shown in About and CTA sections'),
        ),
        migrations.AlterField(
            model_name='about',
            name='short_introduction',
            field=models.TextField(default="I'm a passionate Full Stack Developer with a background in Python full stack development, turned coder. I love building web applications that are clean, useful and user-friendly. I'm always eager to learn, grow and take on new challenges.", help_text='Introduction summary shown in the Hero section'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.PositiveIntegerField(default=0, help_text='Optional proficiency percentage'),
        ),
    ]
