# Generated by Django 4.2.30 on 2026-09-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_resume_skill_is_learning_skill_learning_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='phone',
            field=models.CharField(blank=True, default='+91 7736998984', max_length=50),
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Short skill summary from CV', max_length=255),
        ),
        migrations.AlterField(
            model_name='about',
            name='location',
            field=models.CharField(default='Palakkad, Kerala', max_length=100),
        ),
    ]
