# Generated by Django 4.2.30 on 2026-09-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_about_phone_skill_description_alter_about_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('organization', models.CharField(max_length=250)),
                ('date_or_duration', models.CharField(blank=True, max_length=100)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('certificate_url', models.URLField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'CV Certification',
                'verbose_name_plural': 'CV Certifications',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CVCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('start_date', models.CharField(blank=True, max_length=50)),
                ('end_date', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'CV Course & Learning',
                'verbose_name_plural': 'CV Courses & Learning',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CVEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=250)),
                ('institution', models.CharField(max_length=250)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('start_year', models.CharField(blank=True, max_length=20)),
                ('end_year', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'CV Education',
                'verbose_name_plural': 'CV Education',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CVLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('proficiency', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'CV Language',
                'verbose_name_plural': 'CV Languages',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CVSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CV Summary',
                'verbose_name_plural': 'CV Summary',
            },
        ),
    ]
