# Generated by Django 4.2.30 on 2026-09-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cvcertification_cvcourse_cveducation_cvlanguage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_headline',
            field=models.CharField(default='FROM WORDS TO CODE — CRAFTING REAL-WORLD WEB EXPERIENCES.', help_text='Editorial headline in About Me section', max_length=255),
        ),
        migrations.AddField(
            model_name='about',
            name='about_highlights',
            field=models.TextField(default='Full Stack Focus: Python, Django & React Integration\nDatabase Engineering: MySQL Schema Design & CRUD Logic\nLinguistic Precision: Analytical Thinking & Clear Documentation\nProfessional Mindset: Responsive UI & Maintainable Code', help_text="Newline-separated 'Title: Description' items for highlight cards in About section"),
        ),
        migrations.AddField(
            model_name='about',
            name='availability_status',
            field=models.CharField(default='AVAILABLE FOR HIRING', help_text='Pulsing status badge in Hero section', max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='contact_heading',
            field=models.CharField(default="LET'S WORK TOGETHER", help_text='Main heading in Contact section', max_length=150),
        ),
        migrations.AddField(
            model_name='about',
            name='contact_subtext',
            field=models.TextField(default="I'm actively seeking full-time Full Stack Developer roles, collaborations, and project opportunities. Let's create something reliable, performant, and elegant.", help_text='Subtext description in Contact section'),
        ),
        migrations.AddField(
            model_name='about',
            name='device_mockup',
            field=models.ImageField(blank=True, help_text='Custom device mockup image in Contact section (optional)', null=True, upload_to='devices/'),
        ),
        migrations.AddField(
            model_name='about',
            name='footer_copyright_text',
            field=models.CharField(default='All rights reserved. • Built with React & Django REST Framework.', help_text='Copyright line in Footer', max_length=255),
        ),
        migrations.AddField(
            model_name='about',
            name='greeting_text',
            field=models.CharField(default='Hi, I’m', help_text='Script greeting text above name in Hero', max_length=50),
        ),
        migrations.AddField(
            model_name='about',
            name='hero_highlights',
            field=models.TextField(default='Responsive Development\nClean Code\nUser-Centered Design', help_text='Newline-separated bullet items on the right side of Hero'),
        ),
        migrations.AddField(
            model_name='about',
            name='hero_lead_text',
            field=models.CharField(default='Turning ideas into functional web experiences.', help_text='Right lead text in Hero', max_length=255),
        ),
        migrations.AddField(
            model_name='about',
            name='hero_watermark',
            field=models.CharField(default='PORTFOLIO', help_text='Large background watermark in Hero section', max_length=50),
        ),
        migrations.AddField(
            model_name='about',
            name='side_card_badge',
            field=models.CharField(default='✦ AVAILABLE FOR HIRE', help_text='Badge tag on the side card in About section', max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='side_card_subtext',
            field=models.TextField(default='"I\'m open to new opportunities, freelance projects and collaborations."', help_text='Subtext on the side card in About section'),
        ),
        migrations.AddField(
            model_name='about',
            name='side_card_title',
            field=models.CharField(default='Ready to build something?', help_text='Title on the side card in About section', max_length=150),
        ),
        migrations.AddField(
            model_name='journey',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, default='', help_text="Boxicons class (e.g. 'bx bxl-python', 'bx bxl-react')", max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon_color',
            field=models.CharField(blank=True, default='#D32F2F', help_text="Icon color (e.g. '#3776ab', '#e34f26')", max_length=50),
        ),
        migrations.AddField(
            model_name='skill',
            name='show_in_marquee',
            field=models.BooleanField(default=True, help_text='Display in skill badges'),
        ),
        migrations.AddField(
            model_name='workprocess',
            name='icon',
            field=models.CharField(default='bx bx-check', help_text="Boxicons class (e.g. 'bx bx-search-alt')", max_length=100),
        ),
        migrations.AddField(
            model_name='workprocess',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.PositiveIntegerField(default=0, help_text='Proficiency percentage (0-100)'),
        ),
    ]
