# Generated by Django 4.2.30 on 2026-09-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_about_about_headline_about_about_highlights_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Section 01: Hero & About Me', 'verbose_name_plural': 'Section 01: Hero & About Me'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Form Message', 'verbose_name_plural': 'Contact Form Messages (Inbox)'},
        ),
        migrations.AlterModelOptions(
            name='journey',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Section 04: Education Milestone', 'verbose_name_plural': 'Section 04: Education Milestones'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Section 05: Selected Project', 'verbose_name_plural': 'Section 05: Selected Projects'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Section 02: What I Do (Capability)', 'verbose_name_plural': 'Section 02: What I Do (Capabilities & Services)'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', 'category', 'name'], 'verbose_name': 'Section 03: Skill & Technical Proficiency', 'verbose_name_plural': 'Section 03: Skills & Technical Proficiency'},
        ),
        migrations.AlterModelOptions(
            name='workprocess',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Section 04: Work Process Step', 'verbose_name_plural': 'Section 04: Work Process Steps'},
        ),
        migrations.AddField(
            model_name='about',
            name='about_section_subtitle',
            field=models.TextField(default='A fresher Full Stack Developer driven by curiosity, analytical precision, and practical problem-solving.', help_text='Section subtitle for 01 / ABOUT ME'),
        ),
        migrations.AddField(
            model_name='about',
            name='about_section_title',
            field=models.CharField(default='THE DEVELOPER BEHIND THE CODE', help_text='Section title for 01 / ABOUT ME', max_length=150),
        ),
        migrations.AddField(
            model_name='about',
            name='journey_section_subtitle',
            field=models.TextField(default='A structured timeline of my learning milestones, methodology, and core technical competencies.', help_text='Section subtitle for 04 / EXPERIENCE & EDUCATION'),
        ),
        migrations.AddField(
            model_name='about',
            name='journey_section_title',
            field=models.CharField(default='EDUCATION & PROCESS', help_text='Section title for 04 / EXPERIENCE & EDUCATION', max_length=150),
        ),
        migrations.AddField(
            model_name='about',
            name='projects_section_title',
            field=models.CharField(default='SELECTED PROJECTS', help_text='Section title for 05 / SELECTED PROJECTS', max_length=150),
        ),
        migrations.AddField(
            model_name='about',
            name='services_section_subtitle',
            field=models.TextField(default='Practical, end-to-end full stack development capabilities honed through structured projects and dedicated problem-solving.', help_text='Section subtitle for 02 / WHAT I DO'),
        ),
        migrations.AddField(
            model_name='about',
            name='services_section_title',
            field=models.CharField(default='TECHNICAL CAPABILITIES & SERVICES', help_text='Section title for 02 / WHAT I DO', max_length=150),
        ),
        migrations.AddField(
            model_name='about',
            name='skills_section_subtitle',
            field=models.TextField(default='Core technologies, database engineering, and practical development proficiencies.', help_text='Section subtitle for 03 / TECHNICAL PROFICIENCY'),
        ),
        migrations.AddField(
            model_name='about',
            name='skills_section_title',
            field=models.CharField(default='SKILLS & PROFICIENCY', help_text='Section title for 03 / TECHNICAL PROFICIENCY', max_length=150),
        ),
    ]
