# Generated by Django 4.2.30 on 2026-09-24 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_about_options_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
            ],
            options={
                'verbose_name': 'About Me',
                'verbose_name_plural': 'About Me',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.about',),
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Hero',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.about',),
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-updated_at'], 'verbose_name': 'RESUME / CV', 'verbose_name_plural': 'RESUME / CV'},
        ),
    ]
