# Generated by Django 4.2.30 on 2026-09-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_aboutme_hero_alter_resume_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='WhatsApp', help_text='Name of the social platform (e.g. WhatsApp, GitHub, LinkedIn, Twitter, Instagram, YouTube, Telegram)', max_length=50)),
                ('url', models.CharField(help_text='Full URL or contact link (e.g. https://wa.me/917736998984 or https://github.com/username or mailto:...)', max_length=500)),
                ('icon', models.CharField(blank=True, help_text="Boxicons CSS class (e.g. 'bx bxl-whatsapp', 'bx bxl-github'). Leave empty to auto-detect.", max_length=100)),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order (1 = first, 2 = second, etc.)')),
                ('is_active', models.BooleanField(default=True, help_text='Display this link on your portfolio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Link (Connect Channel)',
                'verbose_name_plural': 'Social Links (Connect Channels)',
                'ordering': ['order', 'id'],
            },
        ),
    ]
