# Generated by Django 4.2.30 on 2026-09-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_sociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='my_role',
            field=models.TextField(blank=True, default='', help_text='Case Study: My Role'),
        ),
        migrations.AddField(
            model_name='project',
            name='overview',
            field=models.TextField(blank=True, default='', help_text='Case Study: Project Overview'),
        ),
        migrations.AddField(
            model_name='project',
            name='problem',
            field=models.TextField(blank=True, default='', help_text='Case Study: Problem / Goal statement'),
        ),
        migrations.AddField(
            model_name='project',
            name='solution',
            field=models.TextField(blank=True, default='', help_text='Case Study: Solution description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Detailed project summary (also used as default overview)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(help_text='Comma-separated or newline-separated technologies', max_length=500),
        ),
    ]
